version: "3"

services:
  api:
    container_name: headhunter_api
    restart: always
    build: .
    ports:
      - "80:5000"
    links:
      - mongo
  mongo:
    container_name: database
    image: mongo
    ports:
      - "27017:27017"
